name: CI
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - name: Use node 20
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'
      - name: Install deps
        run: pnpm install
      - name: Lint
        run: pnpm lint
      - name: Format
        run: pnpm prettier -c .
      # - name: Typecheck
      #   run: pnpm typecheck
